server:
  port: 8081
  servlet:
    context-path: /ovapi/
  tomcat:
      basedir:
        /tmp/tomcat/rtadmin

spring:
  profiles:
    active: dev  #激活环境
  servlet:
     multipart:
        max-file-size: 30MB
        max-request-size: 50MB
  jackson:
    default-property-inclusion: non_null
  application:
    name: ovapi


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.igroupes.rtadmin.entity
  global-config:
    db-config:
      column-format: "`%s`"
      id-type: auto
      logic-delete-value: "now()"
      logic-not-delete-value: "0"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

rest-template:
  maxTotalConnect: 100 #连接池的最大连接数
  maxConnectPerRoute: 200 #单个主机的最大连接数
  connectTimeout: 20000 #连接超时
  readTimeout: 30000 # 读超时


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true