
# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://ovineherd-dev:3306/rt_admin?prepStmtCacheSize=517&cachePrepStmts=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
      username: root
      password: aq12wsde3.
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimemaillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20


rtadmin:
  login:
#    expire-time: 604800000 #7天
    expire-time: 604800000
    token-key: X-TOKEN
  expiry-queue:
    verify-code-interval: 300000 # 5分钟,多久分割一个桶
    verify-code-timeout: 300000 # 校验码多久过期
  request:
    limit-exclude-path: /user/(code|logout|login|info|password|demo_register)|/stat/data|/file/image/.* # 不校验权限的路径,正则表示式,剔除根路径
    log-request-type-filter: POST|PUT|DELETE # 过滤需要的请求类型，正则表达式
    log-exclude-path: /user/password:POST;/stat/data:* # 系统日志排除的路径（如果是通配地址使用$）,格式：路径：请求方式,如果请求方式包含多个中间使用逗号隔开(*表示不限制请求方式)
    #系统日志不记录日志的字段，格式： 请求路径（如果是通配地址使用$）:请求方式,如果请求方式包含多个中间使用逗号隔开(*表示不限制请求方式):字段列表(中间使用逗号隔开),多个请求中间使用
    log-record-exclude-field: /user/login:POST:password,code;/system/user/item/$:*:password
  user:
    default-avatar: http://static.igroupes.com/default_avatar.jpg

  file-store:
    type: com.igroupes.rtadmin.file.core.SimpleFileStore # 类全名
    file-store-dir: /tmp/file/
    store-dir-max-bytes: 10737418240
    download-url-prefix:  http://ovine.igroupes.com/ovapi/file/image
